kind: Pod
apiVersion: v1
metadata:
  name: finance-db
  labels:
    app: finance-db
spec:
  containers:
    - name: finance-db
      image: postgres
      imagePullPolicy: "IfNotPresent"
      envFrom:
        - configMapRef:
            name: finance-db
      ports:
        - containerPort: 5432
